name: Build pollutant JSON

on:
  # Manual trigger
  workflow_dispatch: {}

  # Re-run when calibrated CSVs change
  push:
    branches: [ main ]
    paths:
      - 'calibrated_data/**.csv'

  # Automatic every 10 minutes (UTC)
  schedule:
    - cron: '*/10 * * * *'   # ← every 10 min

concurrency:
  group: build-pollutant-jsonS
  cancel-in-progress: true     # kill prior run if a new one starts

jobs:
  generate-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Generate pollutant_data.json
        run: python scripts/build_pollutant_data.py

      - name: Commit and push artefact
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add pollutant_data.json sensor_metadata.csv || true
          if ! git diff --cached --quiet; then
            git commit -m "Automated pollutant_data.json update ($(date -u +'%Y-%m-%dT%H:%M:%SZ'))"
            git push
          else
            echo "No changes to commit."
          fi
