name: Deploy to shinyapps.io Hourly

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour on the hour
  workflow_dispatch:     # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.1.0"  # Adjust if necessary

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev

      - name: Install required R packages
        run: |
          Rscript -e "install.packages(c('rsconnect','shiny','leaflet','dplyr','readr','lubridate'), repos='https://cloud.r-project.org', 'cran.r-project.org')"

      - name: Load required R libraries
        run: |
          Rscript -e "library(shiny); library(leaflet); library(dplyr); library(readr); library(lubridate)"

      - name: List repository files (for debugging)
        run: |
          echo "Repository root:"
          ls -la
          echo "DESCRIPTION file (if exists):"
          ls -la DESCRIPTION

      - name: Deploy App to shinyapps.io
        env:
          RSCONNECT_ACCOUNT: ${{ secrets.RSCONNECT_ACCOUNT }}
          RSCONNECT_TOKEN: ${{ secrets.RSCONNECT_TOKEN }}
          RSCONNECT_SECRET: ${{ secrets.RSCONNECT_SECRET }}
          RSCONNECT_SERVER: ${{ secrets.RSCONNECT_SERVER }}
        run: |
          Rscript -e "rsconnect::setAccountInfo(name = Sys.getenv('RSCONNECT_ACCOUNT'), token = Sys.getenv('RSCONNECT_TOKEN'), secret = Sys.getenv('RSCONNECT_SECRET'))"
          Rscript -e "rsconnect::deployApp(appDir = '.', appName = 'hugo', server = Sys.getenv('RSCONNECT_SERVER'))"
