name: Update QuantAQ Sensor Data

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes
  workflow_dispatch:        # Allows manual triggering

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install requests pandas pytz

      - name: Run data fetching script
        run: python scripts/fetch_qaq_data.py
        env:
          API_KEY: ${{ secrets.QUANTAQ_API_KEY }}


      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add data/*.csv
          git commit -m "Automated QuantAQ data update at $(date)" || echo "No changes to commit"
          git push origin main

