name: Fetch calibration model
on: workflow_dispatch

jobs:
  download-model:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1. Export AWS creds (also works for R2 because it’s S3-compatible)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4  # <— this one *does* exist
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_ID }}
          aws-region: auto       # any value; R2 ignores it

      # 2. Pull the .obj file from Cloudflare R2
      - name: Download calibration model
        env:
          R2_ACCOUNT_ID:  ${{ secrets.R2_ACCOUNT_ID }}
          R2_BUCKET:      calibration-models
          R2_OBJ_KEY:     2021/Calibration_Models.obj
          DEST_PATH:      models
        run: |
          ./scripts/download_r2_obj.sh
