name: Test R2 download
on: workflow_dispatch        # run manually from the Actions tab

jobs:
  pull-model:
    runs-on: ubuntu-latest

    # R2 credentials available to every step
    env:
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_ID }}
      AWS_DEFAULT_REGION:    us-east-1      # any real region keeps the AWS CLI happy

    steps:
      - uses: actions/checkout@v4           # so the helper script is present

      # 1 ▸ Make a temp dir and expose it via $TMP_DIR
      - name: Create temp dir
        id: mktemp
        run: |
          TMP_DIR="$(mktemp -d)"
          echo "TMP_DIR=$TMP_DIR" >> "$GITHUB_ENV"

      # 2 ▸ Download the model
      - name: Download calibration model from R2
        env:
          R2_ACCOUNT_ID:  ${{ secrets.R2_ACCOUNT_ID }}
          R2_BUCKET:      outdoor-calibrations        # <- your bucket
          R2_OBJ_KEY:     2021/Calibration_Models.obj # <- path **inside** bucket
          DEST_PATH:      ${{ env.TMP_DIR }}
        run: |
          chmod +x scripts/download_r2_obj.sh     # ensure executable bit
          ./scripts/download_r2_obj.sh

      # 3 ▸ Show what we got (sanity check)
      - name: List temp dir
        run: |
          ls -lh "${{ env.TMP_DIR }}"
