name: Fetch calibration model

on:
  workflow_dispatch:   # run manually; add schedule/​push triggers as needed

jobs:
  download-model:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      # Lightweight AWS CLI install
      - name: Set up AWS CLI
        uses: aws-actions/setup-aws-cli@v3

      - name: Download R object from R2
        env:
          AWS_ACCESS_KEY_ID:        ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:    ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          R2_ACCOUNT_ID:            ${{ secrets.R2_ACCOUNT_ID }}   # Cloudflare acct ID
          R2_BUCKET:                calibration-models
          R2_OBJ_KEY:               2021/Calibration_Models.obj
          DEST_PATH:                models              # will create ./models/
          AWS_DEFAULT_REGION:       auto                # satisfies CLI
        run: |
          ./scripts/download_r2_obj.sh

      # (Optional) use the model: readRDS(), commit, upload artifact, etc.
